#!/usr/bin/env bash
# installing nginx on web server

apt-get -y update

apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i 's/8080/80/g' /etc/nginx/sites-available/default

service nginx restart
