#!/usr/bin/env bash
# install nginx web server
# adds 'Hello World!' to index page of web server

sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html

service nginx start
