#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02

sudo apt-get -y install nginx

FILE=/etc/nginx/sites-available/default

sudo sed -i "23i \\\tadd_header X-Served-By \$hostname;" $FILE

sudo service nginx restart
