#!/usr/bin/env bash
# Configure HAProxy for load balancing Nginx servers

# Define the HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 26071-web-01 35.153.52.5:80 check
    server 26071-web-02 100.25.222.164:80 check
"

# Update the package repository cache
apt-get update

# Install necessary packages
apt-get -y install software-properties-common     # Install software-properties-common for add-apt-repository
add-apt-repository -y ppa:vbernat/haproxy-2.8     # Add HAProxy PPA
apt-get update                                    # Update package lists again after adding the repository
apt-get -y install haproxy=2.8*                   # Install HAProxy version 2.8

# Backup the original HAProxy configuration
cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Append the balancer configuration to the HAProxy configuration
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the new configuration
service haproxy restart
