#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.
# in between each iteration of the loop, add a sleep 2

count=0
while [ $count -ge 0 ]; do
	echo "To infinity and beyond";
	sleep 2
done
