#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd.

file="/etc/passwd"
if [[ -f $file ]]; then
	while IFS=: read -r username _ userid _ _  home _; do
		echo "$username:$userid:$home";
	done < "$file";
fi
