#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd.

file="/etc/passwd"
if [[ -f $file ]]; then
	while IFS=: read -r username password userid groupid _ home cmd; do
		echo "The user $username is part of the $groupid gang, lives in $home and rides $cmd. $userid's place is protected by the passcode $password, more info about the user here: $userid";
	done < "$file";
fi
